# Transforming code into idiomatic python
- Replace traditional index manupulation with python core looping idiomatic


In [3]:
# looping over range of numbers - Traditional approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [5]:
# Idiomatic programming
for i in range(6):
    print(i**2,end =" ")

0 1 4 9 16 25 

### Looping over a collection

In [8]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [9]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### Looping backwards

In [10]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [11]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

## Looping in Sorted list

In [13]:
colors=['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
    print(color,end=" ")

yellow red purple green 

 - if x<=y and y<=z
 - if x<=y<=z
 - if x==True
 - if x

### Pandas

In [14]:
import pandas as pd

In [18]:
dt={'Id':[11,12,13,14,15],
    'first_name':['A','B','C','D','E'],
    'company':['aa','bb','cc','dd','ee'],
    'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt=pd.DataFrame(dt)
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [19]:
import os

In [21]:
os.chdir("NIKHIL") # saves to certain location

In [22]:
mydt.to_csv('NIKHIL.csv',index=False)

In [23]:
pwd

'/home/student/anaconda3/NIKHIL'

## Reading the data from csv file

In [28]:
mydata=pd.read_csv('NIKHIL.csv')

In [29]:
print(mydata)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [31]:
mydata1 = pd.read_csv('NIKHIL.csv',skiprows=1,
                     names=["custId","Name","company","Address"])


In [32]:
print(mydata1)

   custId Name company Address
0      11    A      aa     Hyd
1      12    B      bb     Hyd
2      13    C      cc     Hyd
3      14    D      dd     Hyd
4      15    E      ee     Hyd


## problems to be solved:-
- print only two columns
- print the large value from custid column--max
- print the least value from column--min
- average of custID colulmn -- sum(li)/len(li)

## Numpy-Working with multi Dimensional array
- numpy arrays is a bit like python list
- numpy arrays is a one of Datastructure of numpy lib
- it's short name for "numeric python" or "numerical python"

In [33]:
import numpy as np  # importing numpy package

In [34]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [35]:
array=np.array(li)  #converrting the list into array using np.array()
print(array)

[1 2 3 4 5]


In [38]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [41]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [43]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
